services:
  postgres:
    image: postgres:16-alpine
    container_name: mini-wms-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_DB: mini_wms
    ports:
      - "5432:5432"
    volumes:
      - mini-wms-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mini-wms-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  mini-wms-data:
